#!/usr/bin/env ruby
# vim: set filetype=ruby:
$: << File.expand_path("../../lib/", __FILE__)

require 'yaml'
require 'readline'
require 'bindot2braille'

ascii_font = YAML.load(open(File.expand_path('../../fontdata/misaki.yml', __FILE__)))

while input = Readline.readline('YAPPY> ')
  case input
  when 'quit', 'exit'
    break
  else
    input.split(//).map { |c|
      BinDot2Braille.convert(4, 8, ascii_font[c])
    }
    .each { |c|
      print c[0].join
    }
    .tap { puts }
    .each { |c|
      print c[1].join
    }
    .tap { puts }
  end
end

