#!/usr/bin/env ruby
# vim: set filetype=ruby:
$: << File.expand_path("../../lib/", __FILE__)

require 'yaml'
require 'readline'
require 'bindot2braille'

font_table = YAML.load(
  open(File.expand_path('../../fontdata/misaki.yml', __FILE__)).read +
  open(File.expand_path('../../fontdata/kanji.yml', __FILE__)).read)

while input = Readline.readline('YAPPY> ')
  case input
  when 'quit', 'exit'
    break
  else
    input.split(//).reject { |c|
      font_table[c].nil?
    }
    .map { |c|
      bindot = font_table[c].split("\n")
      {
        width: bindot[0].size,
        height: bindot.size,
        bindot: bindot.join
      }
    }
    .map { |data|
      BinDot2Braille.convert(data[:width], data[:height], data[:bindot])
    }
    .each { |c|
      print c[0].join
    }
    .tap { puts }
    .each { |c|
      print c[1].join
    }
    .tap { puts }
  end
end

